# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=80)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='idea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.Idea'),
        ),
    ]
