# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 14:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0002_auto_20161118_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='sell_price',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_text',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message=b'Length has to be more than 3')]),
        ),
    ]
